### ISSUE TITLE
identify additional metadata / configuration data needed for metabolomics including the use of blanks

### ISSUE THREAD

**Issue by dehays** [microbiomedata/metaMS#4]
@corilo  Move this issue to whichever issue queue you deem appropriate.

Once you have defined the necessary metadata / configuration data - there would be nmdc-schema issues to align those needs with changes to the metabolomics metadata specified in the schema

**Comment by corilo** [comment]
@mslarae13 could you please help with the necessary metadata definitions?

**Comment by mslarae13** [comment]
@yuricorilo 
Yes! I definitely can! This I think would fall under preparation metadata. Could we chat about details and a path forward?

**Comment by ssarrafan** [comment]
@yuricorilo @mslarae13 @dehays I was going to move this to the May sprint since it's not done.  Let me know if you're not planning to work on it during May otherwise I'll move it over.

**Comment by ssarrafan** [comment]
From: Setareh Sarrafan <ssarrafan@lbl.gov>
Date: Mon, May 3, 2021 at 9:12 AM
Subject: Re: [EXTERNAL] GitHub issues
To: Hu, Bin <bhu@lanl.gov>
Cc: Kjiersten Fagnan <kmfagnan@lbl.gov>


Hi Bin,

Is it ok if I move the open workflow related GitHub issues to the May sprint?  If there are any that you don't plan to work on in May let me know, or if there are ones that you made some progress and would like to close let me know, otherwise I was planning to move the following to May sprint:
 

Thanks, Setareh

On Fri, Apr 23, 2021 at 1:03 PM Setareh Sarrafan <ssarrafan@lbl.gov> wrote:
Thanks for the update Bin.  If you'd like Michal to get a GitHub account let me know.  For now I'll leave the GitHub issues as they are and we'll see how it goes next week. 
Best, Set

**Comment by ssarrafan** [comment]
@corilo should this issue be closed or moved to the June sprint?

**Comment by ssarrafan** [comment]
Moving to June per @yuricorilo on Slack

**Comment by ssarrafan** [comment]
Will be closed by @mslarae13 after a meeting tomorrow.

**Comment by mslarae13** [comment]
Proteomics: Agilent tune mix and a complex proteome are used to check the run, but are not used in analyses
https://github.com/microbiomedata/metaMS/issues/9

metabolomics: agilent tune mix, see follow up issuse for confirmation of prep
-blanks, FAMES standard or alkane mixer, see follow up issue for confirmation or prep & what is used at PNNL
https://github.com/microbiomedata/metaMS/issues/8


NOM: blanks, FAMES standard or alkane mixer, see follow up issue for confirmation
-QC, SURFA internal standard. see follow up issue for confirmation of prep
https://github.com/microbiomedata/metaMS/issues/10
